name: api_client
description: Package for managing api requests
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

  connectivity: ^3.0.6
  dio: 5.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.5.3
  mocktail: ^0.2.0
  build_runner: ^2.0.4
  json_serializable: ^6.5.3

